name: uuid
version: 4.0.0-beta1
description: >
  RFC4122 (v1, v4, v5) UUID Generator and Parser for all Dart platforms (Web, VM, Flutter)
homepage: https://github.com/Daegalus/dart-uuid
environment:
  sdk: ">=2.14.0 <3.0.0"
dependencies:
  crypto: "^3.0.2"
  sprintf: "^6.0.0"
dev_dependencies:
  pedantic: ">=1.11.1"
  test: ^1.21.1
